inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*"

Style/FormatStringToken:
  EnforcedStyle: unannotated

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

